Add: '+'
Subtract: '−'
Times: '×'
Divide: '÷'
Surplus: '%'
Logarithm: 'log'
Power: 'aⁿ'
And: '&'
Nand: '!&'
Or: 'ǀǀ'
Nor: '!ǀǀ'
Xor: '⊕'
EqualTo: '='
NotEqual: '≠'
GreaterThan: '>'
GreaterThanOrEqualTo: '≥'
LessThan: '<'
LessThanOrEqualTo: '≤'
Assignment: '→'
#Compound:
Loop: '↻'
Conditional: 'if'
Variable: 'a'
Constant: '0'
